message(STATUS "include PathHelp.cmake")

message("PathHelp.cmake:    BEFORE REPLACE(PROJECT_BINARY_DIR): ${PROJECT_BINARY_DIR}")
STRING( REGEX REPLACE "/proj$" "" PROJECT_SOURCE_DIR_FATHER ${PROJECT_BINARY_DIR} )
message("PathHelp.cmake:    AFTER REPLACE(PROJECT_SOURCE_DIR_FATHER): ${PROJECT_SOURCE_DIR_FATHER}")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR_FATHER}/bin")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_SOURCE_DIR_FATHER}/bin/debug")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_SOURCE_DIR_FATHER}/bin/release")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR_FATHER}/lib")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${PROJECT_SOURCE_DIR_FATHER}/lib/debug")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PROJECT_SOURCE_DIR_FATHER}/lib/release")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR_FATHER}/lib")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${PROJECT_SOURCE_DIR_FATHER}/lib/debug")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PROJECT_SOURCE_DIR_FATHER}/lib/release")

